apiVersion: osb.servicefabrik.io/v1alpha1
kind: SFService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: &id '24731fb8-7b84-5f57-914f-c3d55d793dd4'
spec:
  name: &name postgresql
  id: *id
  description: &description 'Postgresql for internal development, testing, and documentation purposes of the Service Fabrik'
  tags:
  - 'postgresql'
  requires: []
  bindable: true
  instanceRetrievable: true
  bindingRetrievable: true
  metadata:
    displayName: 'PostgreSQL'
    longDescription: *description
    providerDisplayName: 'SAP SE'
    documentationUrl: 'https://sap.com/'
    supportUrl: 'https://sap.com/'
  dashboardClient:
    id: postgresql-dashboard-client-id
    secret: postgresql-dashboard-client-secret
    redirectURI: 'https://sap.com/'
  planUpdatable: true
  context:
    serviceFabrik:
      backupEnabled: false
    operator:
      image: "servicefabrikjenkins/postgresql"
      tag: "latest"
      port: 8080
