# Default values for service-fabrik-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

cluster:
  host: sf.ingress.sf21-intop.interop.shoot.canary.k8s-hana.ondemand.com
  ssl: true
  sslsecret: wildcard-cert-ssl-tls        

broker:
  port: 9293
  username: broker
  password: secret
  enable_namespaced_separation: true
  services_namespace: "services"
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  quota:
    enabled: false
    oauthDomain: https://myauth-domain.com
    serviceDomain: https://my-tenant-onboarding.com
    username: quota_user
    password: quota_password
  image:
    repository: servicefabrikjenkins/service-fabrik-broker
    tag: 0.12.1
    pullPolicy: Always
  service:
    type: LoadBalancer

quota_app:
  port: 9296
  username: quota
  password: secret
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    type: ClusterIP

interoperator:
  image:
    repository: servicefabrikjenkins/service-fabrik-interoperator
    tag: 0.12.1
    pullPolicy: Always
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  config:
    instanceWorkerCount: 2
    bindingWorkerCount: 4
    schedulerWorkerCount: 2
    provisionerWorkerCount: 2

operator_apis:
  port: 9297
  username: admin
  password: secret
  #host: op.ingress.sf21-intop.interop.shoot.canary.k8s-hana.ondemand.com
  image:
    repository: servicefabrikjenkins/operatorapis
    tag: 0.12.1
    pullPolicy: Always
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    type: ClusterIP
  ssl: true
  sslsecret: op-api-ssl-cert


#imagePullSecrets:
#- name: docker-dmz
#- name: docker-dmz2
