# Default values for service-fabrik-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

cluster:
  host: sf.ingress.sf21-intop.interop.shoot.canary.k8s-hana.ondemand.com
  ssl: true
  sslsecret: wildcard-cert-ssl-tls        

broker:
  port: 9293
  username: broker
  password: secret
  enable_namespaced_separation: true
  services_namespace: "services"
  allow_concurrent_operations: true
  allow_concurrent_binding_operations: true
  send_binding_metadata: true
  
  # override the global replicaCount just for broker
  replicaCount: 4
  resources:
    limits:
      cpu: 800m
      memory: 256Mi
    requests:
      cpu: 400m
      memory: 128Mi
  quota:
    enabled: false
    oauthDomain: https://myauth-domain.com
    serviceDomain: https://my-tenant-onboarding.com
    username: quota_user
    password: quota_password
    # regions:
    #   eu10:
    #     oauthDomain: https://myauth-domain.com
    #     serviceDomain: https://my-tenant-onboarding.com
    #     username: quota_user
    #     password: quota_password
    #   eu20:
    #     oauthDomain: https://myauth-domain.com
    #     serviceDomain: https://my-tenant-onboarding.com
    #     username: quota_user
    #     password: quota_password
  image:
    repository: servicefabrikjenkins/service-fabrik-broker
    tag: 0.15.0
    pullPolicy: Always
  service:
    type: LoadBalancer

quota_app:
  port: 9296
  username: quota
  password: secret

  # override the global replicaCount just for quota_app
  #replicaCount: 1
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP

interoperator:
  image:
    repository: servicefabrikjenkins/service-fabrik-interoperator
    tag: 0.15.0
    pullPolicy: Always

  # override the global replicaCount just for interoperator components
  #replicaCount: 2
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    instanceWorkerCount: 2
    bindingWorkerCount: 4
    schedulerWorkerCount: 2
    provisionerWorkerCount: 2

  provisioner:
    resources:
      limits:
        cpu: 1800m
        memory: 512Mi
      requests:
        cpu: 600m
        memory: 256Mi

  scheduler:
    resources:
      limits:
        cpu: 400m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

  multiclusterdeployer:
    resources:
      limits:
        cpu: 1200m
        memory: 128Mi
      requests:
        cpu: 400m
        memory: 64Mi

operator_apis:
  enabled: true
  port: 9297
  username: admin
  password: secret
  #host: op.ingress.sf21-intop.interop.shoot.canary.k8s-hana.ondemand.com
  image:
    repository: servicefabrikjenkins/operatorapis
    tag: 0.15.0
    pullPolicy: Always

  # override the global replicaCount just for operator apis
  #replicaCount: 2
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    type: ClusterIP
  ssl: true
  sslsecret: op-api-ssl-cert


#imagePullSecrets:
#- name: docker-dmz
#- name: docker-dmz2
