# Default values for service-fabrik-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

cluster:
  host: sf.ingress.sf21-intop.interop.shoot.canary.k8s-hana.ondemand.com
  ssl: true
  sslsecret: wildcard-cert-ssl-tls        

broker:
  port: 9293
  username: broker
  password: secret
  enable_namespaced_separation: true
  services_namespace: "services"
  quota:
    enabled: false
    oauthDomain: https://myauth-domain.com
    serviceDomain: https://my-tenant-onboarding.com
    username: quota_user
    password: quota_password
  image:
    repository: servicefabrikjenkins/service-fabrik-broker
    tag: 0.5.1
    pullPolicy: Always
  service:
    type: LoadBalancer

interoperator:
  image:
    repository: servicefabrikjenkins/service-fabrik-interoperator
    tag: 0.5.1
    pullPolicy: Always
  resources:
    limits:
      cpu: 800m
      memory: 512Mi
    requests:
      cpu: 400m
      memory: 256Mi
  config:
    instanceWorkerCount: 2
    bindingWorkerCount: 4
    schedulerWorkerCount: 2
    provisionerWorkerCount: 2
    schedulerType: label-selector

#imagePullSecrets:
#- name: docker-dmz
#- name: docker-dmz2