{{ $name := "" }}
{{- with .instance.metadata.name }} {{ $name = . }} {{ end }}
{{- $state := "in_queue" }}
{{- with .instance.metadata.labels.state }} {{ $state = . }} {{ end }}
{{- $serviceId := "" }}
{{- $planId := "" }}
{{- $organizationGuid := "" }}
{{- $spaceGuid := "" }}
{{- $context := "{}" }}
{{- $params := "{}" }}
{{- $previousValues := "{}" }}
{{- with .instance.spec }}
  {{- with .serviceId }}
    {{- $serviceId = . }}
  {{- end }}
  {{- with .planId }}
    {{- $planId = . }}
  {{- end }}
  {{- with .organizationGuid }}
    {{- $organizationGuid = . }}
  {{- end }}
  {{- with .spaceGuid }}
    {{- $spaceGuid = . }}
  {{- end }}
  {{- with .context }}
    {{- $context = (marshalJSON .) }}
  {{- end }}
  {{- with .parameters }}
    {{- $params = (marshalJSON .) }}
  {{- end }}
  {{- with .previousValues }}
    {{- $previousValues = (marshalJSON .) }}
  {{- end }}
{{- end }}
{{- $options := (printf "{ \"service_id\": \"%s\", \"plan_id\": \"%s\", \"organization_guid\": \"%s\", \"space_guid\": \"%s\", \"context\": %s, \"parameters\": %s }" $serviceId $planId $organizationGuid $spaceGuid $context $params ) | quote }}
{{- with .instance.spec.previousValues }}
  {{- $options = (printf "{ \"service_id\": \"%s\", \"plan_id\": \"%s\", \"organization_guid\": \"%s\", \"space_guid\": \"%s\", \"context\": %s, \"parameters\": %s, \"previous_values\": %s }" $serviceId $planId $organizationGuid $spaceGuid $context $params $previousValues ) | quote  }}
{{- end }}
apiVersion: deployment.servicefabrik.io/v1alpha1
kind: Director
metadata:
  labels:
    state: {{ $state }}
  name: {{ $name }}
spec:
  options: {{ $options }}
status:
  state: {{ $state }}