{{ $name := "" }}
{{- with .binding.metadata.name }} {{ $name = . }} {{ end }}
{{- $state := "in_queue" }}
{{- with .binding.status.state }} {{ $state = . }} {{ end }}
{{- $serviceId := "" }}
{{- $planId := "" }}
{{- $context := "{}" }}
{{- $params := "{}" }}
{{- $acceptsIncomplete := false }}
{{- $appGuid := "" }}
{{- $bindResource := "{}" }}
{{- $id := "" }}
{{- $instanceId := "" }}
{{- with .binding.spec }}
  {{- with .serviceId }}
    {{- $serviceId = . }}
  {{- end }}
  {{- with .planId }}
    {{- $planId = . }}
  {{- end }}
  {{- with .context }}
    {{- $context = (marshalJSON .) }}
  {{- end }}
  {{- with .parameters }}
    {{- $params = (marshalJSON .) }}
  {{- end }}
  {{- with .acceptsIncomplete }}
    {{- $acceptsIncomplete = . }}
  {{- end }}
  {{- with .appGuid }}
    {{- $appGuid = . }}
  {{- end }}
  {{- with .bindResource }}
    {{- $bindResource = (marshalJSON .) }}
  {{- end }}
  {{- with .id }}
    {{- $id = . }}
  {{- end }}
  {{- with .instanceId }}
    {{- $instanceId = . }}
  {{- end }}
{{- end }}


apiVersion: bind.servicefabrik.io/v1alpha1
kind: DockerBind
metadata:
  labels:
    state: {{ $state }}
    instance_guid: {{ $instanceId }}
  name: {{ $name }}
spec:
  options: {{ (printf "{ \"service_id\": \"%s\", \"plan_id\": \"%s\", \"app_guid\": \"%s\", \"bind_resource\": %s, \"context\": %s, \"binding_id\": \"%s\", \"parameters\": %s, \"accepts_incomplete\": %t }" $serviceId $planId $appGuid $bindResource $context $id $params $acceptsIncomplete) | quote }}
status:
  state: {{ $state }}